//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESXTranslator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RESXTranslator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate.
        /// </summary>
        internal static string ButtonTranslate {
            get {
                return ResourceManager.GetString("ButtonTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clearwindowcontent_6304 {
            get {
                object obj = ResourceManager.GetObject("Clearwindowcontent_6304", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to translate {0} to {1}?.
        /// </summary>
        internal static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation....
        /// </summary>
        internal static string ConfirmMessageCaption {
            get {
                return ResourceManager.GetString("ConfirmMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy_6524 {
            get {
                object obj = ResourceManager.GetObject("Copy_6524", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        internal static string DefaultAllFilter {
            get {
                return ResourceManager.GetString("DefaultAllFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resx.
        /// </summary>
        internal static string DefaultExtension {
            get {
                return ResourceManager.GetString("DefaultExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Resource Files.
        /// </summary>
        internal static string DefaultFileDlgTitle {
            get {
                return ResourceManager.GetString("DefaultFileDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESW Files (*.resw)|*.resw|RESX Files (*.resx)|*.resx.
        /// </summary>
        internal static string DefaultFilter {
            get {
                return ResourceManager.GetString("DefaultFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory {0} does not exists..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source RESX Root.
        /// </summary>
        internal static string DirSearch {
            get {
                return ResourceManager.GetString("DirSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source RESX File.
        /// </summary>
        internal static string DirUnSearch {
            get {
                return ResourceManager.GetString("DirUnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exists..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items match your search..
        /// </summary>
        internal static string FileNotFoundWithFilter {
            get {
                return ResourceManager.GetString("FileNotFoundWithFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file is created..
        /// </summary>
        internal static string FileSaveMessage {
            get {
                return ResourceManager.GetString("FileSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation....
        /// </summary>
        internal static string FileSaveMessageCaption {
            get {
                return ResourceManager.GetString("FileSaveMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GenerateTable_317 {
            get {
                object obj = ResourceManager.GetObject("GenerateTable_317", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading available languages for translation from Microsoft Translator ....
        /// </summary>
        internal static string LoadLanguageToCombox {
            get {
                return ResourceManager.GetString("LoadLanguageToCombox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translation.
        /// </summary>
        internal static string MSAPITranslation {
            get {
                return ResourceManager.GetString("MSAPITranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string MSAPITranslationLangName {
            get {
                return ResourceManager.GetString("MSAPITranslationLangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to translations.
        /// </summary>
        internal static string MSAPITranslations {
            get {
                return ResourceManager.GetString("MSAPITranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string MSAPITranslationText {
            get {
                return ResourceManager.GetString("MSAPITranslationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flaggedTokens.
        /// </summary>
        internal static string MSBingFlaggedTokens {
            get {
                return ResourceManager.GetString("MSBingFlaggedTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset.
        /// </summary>
        internal static string MSBingOffset {
            get {
                return ResourceManager.GetString("MSBingOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to score.
        /// </summary>
        internal static string MSBingScore {
            get {
                return ResourceManager.GetString("MSBingScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suggestion.
        /// </summary>
        internal static string MSBingSuggestion {
            get {
                return ResourceManager.GetString("MSBingSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suggestions.
        /// </summary>
        internal static string MSBingSuggestions {
            get {
                return ResourceManager.GetString("MSBingSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string MSBingText {
            get {
                return ResourceManager.GetString("MSBingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        internal static string MSBingToken {
            get {
                return ResourceManager.GetString("MSBingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Nothing to save..
        /// </summary>
        internal static string NothingToSave {
            get {
                return ResourceManager.GetString("NothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error : Nothing to translate..
        /// </summary>
        internal static string NothingToTranslate {
            get {
                return ResourceManager.GetString("NothingToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFileDialog_692 {
            get {
                object obj = ResourceManager.GetObject("OpenFileDialog_692", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paste_6520_32 {
            get {
                object obj = ResourceManager.GetObject("Paste_6520_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until finished reading the file from {0}..
        /// </summary>
        internal static string ReadingSourceResxFile {
            get {
                return ResourceManager.GetString("ReadingSourceResxFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecalculatePageBreaks_268 {
            get {
                object obj = ResourceManager.GetObject("RecalculatePageBreaks_268", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utf-8.
        /// </summary>
        internal static string RequestHeaderAcceptCharSet {
            get {
                return ResourceManager.GetString("RequestHeaderAcceptCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string RequestHeaderAcceptedLanguage {
            get {
                return ResourceManager.GetString("RequestHeaderAcceptedLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept-Language.
        /// </summary>
        internal static string RequestHeaderAcceptLanguage {
            get {
                return ResourceManager.GetString("RequestHeaderAcceptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string RequestHeaderContentJson {
            get {
                return ResourceManager.GetString("RequestHeaderContentJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string RequestHeaderContentUrlEncoded {
            get {
                return ResourceManager.GetString("RequestHeaderContentUrlEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocp-Apim-Subscription-Key.
        /// </summary>
        internal static string RequestHeaderSubscriptionKey {
            get {
                return ResourceManager.GetString("RequestHeaderSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResultstoFile_9946 {
            get {
                object obj = ResourceManager.GetObject("ResultstoFile_9946", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Saveall_6518 {
            get {
                object obj = ResourceManager.GetObject("Saveall_6518", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is created..
        /// </summary>
        internal static string SaveResourceFileMessage {
            get {
                return ResourceManager.GetString("SaveResourceFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5000.
        /// </summary>
        internal static string StringMaxLength {
            get {
                return ResourceManager.GetString("StringMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length exceeds maximum translation length..
        /// </summary>
        internal static string StringMaxLengthError {
            get {
                return ResourceManager.GetString("StringMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total files {0} are loaded from {1}..
        /// </summary>
        internal static string TotalFileCountRead {
            get {
                return ResourceManager.GetString("TotalFileCountRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is finished without error...!.
        /// </summary>
        internal static string TranslateingEnd {
            get {
                return ResourceManager.GetString("TranslateingEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation is incompleted..
        /// </summary>
        internal static string TranslateingIncomplete {
            get {
                return ResourceManager.GetString("TranslateingIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate from {0}({1}) to {2}({3})..
        /// </summary>
        internal static string TranslateingStart {
            get {
                return ResourceManager.GetString("TranslateingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translating line no. {0} of file count {1}..
        /// </summary>
        internal static string TranslatingLineNo {
            get {
                return ResourceManager.GetString("TranslatingLineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon translation {
            get {
                object obj = ResourceManager.GetObject("translation", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
